cookie:
  expiry_days: 30
  key: some_signature_key
  name: blog_generator_auth
credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Administrator
      password: $2b$12$Qj7H6hg/yX51xuXIVVpGpeTDAT6vpJrAjNa4iUP4L6ObbRwiyT/uy
preauthorized:
  emails: []
